databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: forget_me_not
    runtime: python
    buildCommand: "./build.sh"
    startCommand: 'gunicorn forget_me_not.asgi:application -k uvicorn.workers.UvicornWorker' #プロジェクト名に変更

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG  # この行を追加
        value: "False"  # 本番環境では通常Falseに設定  