# Generated by Django 5.1.5 on 2025-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forget_me_not_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="memo",
            name="categories",
            field=models.ManyToManyField(to="forget_me_not_app.category"),
        ),
    ]
