# Generated by Django 5.1.5 on 2025-02-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forget_me_not_app", "0004_memo_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memo",
            old_name="user",
            new_name="owner",
        ),
    ]
